version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=abdulrahman
      - POSTGRES_PASSWORD=bundaar
      - POSTGRES_DB=db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  postgres:
    name: db
  cache:
    driver: local